apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-api-gateway
  name: mender-api-gateway
spec:
  containers:
  - env:
    - name: ALLOWED_HOSTS
      value: my-gateway-dns-name
    image: mendersoftware/api-gateway:master
    name: mender-api-gateway
    ports:
    - containerPort: 443
    resources: {}
    volumeMounts:
    - mountPath: /var/www/mendersoftware/cert/cert.crt
      name: mender-api-gateway-claim0
      readOnly: true
    - mountPath: /var/www/mendersoftware/cert/private.key
      name: mender-api-gateway-claim1
      readOnly: true
  restartPolicy: OnFailure
  volumes:
  - name: mender-api-gateway-claim0
    persistentVolumeClaim:
      claimName: mender-api-gateway-claim0
      readOnly: true
  - name: mender-api-gateway-claim1
    persistentVolumeClaim:
      claimName: mender-api-gateway-claim1
      readOnly: true
status: {}
