apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-redis
  name: mender-redis
spec:
  containers:
  - command:
    - /redis/entrypoint.sh
    image: redis:5-alpine3.8
    name: mender-redis
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/redis
      name: mender-redis-db
    - mountPath: /etc/redis/redis.conf
      name: mender-redis-claim1
      subPath: redis.conf
    - mountPath: /redis/entrypoint.sh
      name: mender-redis-claim2
      subPath: entrypoint.sh
      readOnly: false
  restartPolicy: OnFailure
  volumes:
  - name: mender-redis-db
    persistentVolumeClaim:
      claimName: mender-redis-db
  - name: mender-redis-claim1
    configMap:
      name: redis-conf 
#    persistentVolumeClaim:
#      claimName: mender-redis-claim1
  - name: mender-redis-claim2
    configMap:
      name: redis-entrypoint
      defaultMode: 0755
#    persistentVolumeClaim:
#      claimName: mender-redis-claim2
status: {}
