apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-mongo
  name: mender-mongo
spec:
  containers:
  - image: mongo:3.4
    name: mender-mongo
    resources: {}
    volumeMounts:
    - mountPath: /data/db
      name: mender-db
  restartPolicy: OnFailure
  volumes:
  - name: mender-db
    persistentVolumeClaim:
      claimName: mender-db
status: {}
