apiVersion: v1
kind: Service
metadata:
  name: mender-conductor
  labels:
    io.kompose.service: mender-conductor
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    io.kompose.service: mender-conductor
