apiVersion: v1
kind: Service
metadata:
  name: mender-redis
  labels:
    io.kompose.service: mender-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    io.kompose.service: mender-redis
