apiVersion: v1
kind: Service
metadata:
  name: mender-mongo
  labels:
    io.kompose.service: mender-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    io.kompose.service: mender-mongo
