apiVersion: v1
kind: Service
metadata:
  name: mender-device-auth
  labels:
    io.kompose.service: mender-device-auth
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    io.kompose.service: mender-device-auth
