apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-useradm
  name: mender-useradm
spec:
  containers:
  - args:
    - server
    - --automigrate
    image: mendersoftware/useradm:master
    name: mender-useradm
    resources: {}
    volumeMounts:
    - mountPath: /etc/useradm/rsa/private.pem
      name: mender-useradm-claim0
      readOnly: true
  restartPolicy: OnFailure
  volumes:
  - name: mender-useradm-claim0
    persistentVolumeClaim:
      claimName: mender-useradm-claim0
      readOnly: true
status: {}
