apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-device-auth
  name: mender-device-auth
spec:
  containers:
  - args:
    - server
    - --automigrate
    image: mendersoftware/deviceauth:master
    name: mender-device-auth
    resources: {}
    volumeMounts:
    - mountPath: /etc/deviceauth/rsa/private.pem
#    - mountPath: /etc/useradm/rsa/private.pem
      name: mender-device-auth-claim0
      subPath: private.pem
      readOnly: true
  restartPolicy: OnFailure
  volumes:
  - name: mender-device-auth-claim0
    configMap:
      name: mender-device-auth
#    persistentVolumeClaim:
#      claimName: mender-device-auth-claim0
#      readOnly: true
status: {}
