apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-elasticsearch
  name: mender-elasticsearch
spec:
  containers:
  - image: elasticsearch:5-alpine
    name: mender-elasticsearch
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: mender-elasticsearch-db
    - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
      name: mender-elasticsearch-claim1
      subPath: elasticsearch.yml
  restartPolicy: OnFailure
  volumes:
  - name: mender-elasticsearch-db
    persistentVolumeClaim:
      claimName: mender-elasticsearch-db
  - name: mender-elasticsearch-claim1
    configMap:
      name: mender-elasticsearch
#    persistentVolumeClaim:
#      claimName: mender-elasticsearch-claim1
status: {}
