apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-conductor
  name: mender-conductor
spec:
  containers:
  - image: mendersoftware/mender-conductor:master
    name: mender-conductor
    resources: {}
  restartPolicy: OnFailure
status: {}
