apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mender-inventory
  name: mender-inventory
spec:
  containers:
  - args:
    - server
    - --automigrate
    image: mendersoftware/inventory:master
    name: mender-inventory
    resources: {}
  restartPolicy: OnFailure
status: {}
