apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml -f ../docker-compose.storage.minio.yml
      -f ../template/prod.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - server
        - /export
        env:
        - name: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
        image: minio/minio:RELEASE.2018-09-25T21-34-43Z
        name: minio
        resources: {}
        volumeMounts:
        - mountPath: /export
          name: mender-artifacts
      restartPolicy: Always
      volumes:
      - name: mender-artifacts
        persistentVolumeClaim:
          claimName: mender-artifacts
status: {}
